name: simple_firebase_crud_cubit
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  flutterfire_ui: ^0.4.3+12
  page_indicator: ^0.4.1
  get_it: ^7.3.0
  google_sign_in: ^5.4.2
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.1


flutter:


  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
